version: '3.9'
services:
    bot:
        build:
            context: ''
            dockerfile: docker/Dockerfile
        container_name: ithappens_bot
        restart: always
        networks:
        - nginx-network

networks:
  nginx-network:
    external: true
    name: nginx-network
